export const rows = [
  {
    id: 1,
    username: "Jon Snow",
    avatar: "",
    email: "joh@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Arya Stark",
    avatar: "",
    email: "arya@gmail.com",
    status: "active",
    transaction: "$520.00",
  },
  {
    id: 3,
    username: "Daenerys Targaryen",
    avatar: "",
    email: "dany@gmail.com",
    status: "active",
    transaction: "$420.00",
  },
  {
    id: 4,
    username: "Cersei Lannister",
    avatar: "",
    email: "cer@gmail.com",
    status: "active",
    transaction: "$820.00",
  },
  {
    id: 5,
    username: "Ned Stark",
    avatar: "",
    email: "ned@gmail.com",
    status: "active",
    transaction: "$920.00",
  },
  {
    id: 6,
    username: "Jon Snow",
    avatar: "",
    email: "joh@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Arya Stark",
    avatar: "",
    email: "arya@gmail.com",
    status: "active",
    transaction: "$520.00",
  },
  {
    id: 8,
    username: "Daenerys Targaryen",
    avatar: "",
    email: "dany@gmail.com",
    status: "active",
    transaction: "$420.00",
  },
  {
    id: 9,
    username: "Cersei Lannister",
    avatar: "",
    email: "cer@gmail.com",
    status: "active",
    transaction: "$820.00",
  },
  {
    id: 10,
    username: "Ned Stark",
    avatar: "",
    email: "ned@gmail.com",
    status: "active",
    transaction: "$920.00",
  },
];
