export const productsRows = [
  {
    id: 1,
    name: "Product 1",
    avatar: "",
    stock: "123",
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    name: "Product 2 ",
    avatar: "",
    stock: "343",
    status: "active",
    price: "$520.00",
  },
  {
    id: 3,
    name: "Product 3",
    avatar: "",
    stock: "545",
    status: "active",
    price: "$420.00",
  },
  {
    id: 4,
    name: "Product 4 ",
    avatar: "",
    stock: "244",
    status: "active",
    price: "$820.00",
  },
  {
    id: 5,
    name: "Product 5",
    avatar: "",
    stock: "323",
    status: "active",
    price: "$920.00",
  },
  {
    id: 6,
    name: "Product 6",
    avatar: "",
    stock: "324",
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    name: "Product 7",
    avatar: "",
    stock: "7876",
    status: "active",
    price: "$520.00",
  },
  {
    id: 8,
    name: "Product 8",
    avatar: "",
    stock: "755",
    status: "active",
    price: "$420.00",
  },
  {
    id: 9,
    name: "Product 9",
    avatar: "",
    stock: "6685",
    status: "active",
    price: "$820.00",
  },
  {
    id: 10,
    name: "Product 10",
    avatar: "",
    stock: "123",
    status: "active",
    price: "$920.00",
  },
];
